apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-my-envs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/NoyLevi24/AmiranetGitOps.git
      revision: HEAD
      files:
      - path: "manifests/amiranet-appset/env-config/**/config.json"       
  template:      
    metadata:
      name: '{{.env}}' 
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application could be in another repository
      sources:
        - repoURL: https://github.com/NoyLevi24/AmiranetGitOps.git
          targetRevision: HEAD
          path: ./manifests/amiranet-appset/my-chart
          helm:
            valueFiles:
            - $values/manifests/amiranet-appset/my-values/common-values.yaml          
            - $values/manifests/amiranet-appset/my-values/app-version/{{.version}}-values.yaml               
            - $values/manifests/amiranet-appset/my-values/env-type/{{.type}}-values.yaml  
            - $values/manifests/amiranet-appset/my-values/regions/{{.region}}-values.yaml                
            - $values/manifests/amiranet-appset/my-values/envs/{{.env}}-values.yaml
        - repoURL: https://github.com/NoyLevi24/AmiranetGitOps.git
          targetRevision: HEAD
          ref: values
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.env}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: 
          prune: true 
          selfHeal: true 
    
