apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "82.15.1"
    helm:
      releaseName: prometheus-stack
      values: |
        fullnameOverride: prometheus-stack

        ## Grafana Configuration
        grafana:
          adminPassword: "admin" # מומלץ להחליף ל-Secret ב-Production
          defaultDashboardsTimezone: Asia/Jerusalem
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL

        ## Prometheus Instance & Discovery
        prometheus:
          prometheusSpec:
            # הגדרה קריטית לגילוי אוטומטי של ServiceMonitors בפרויקטים שלך
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            podMonitorSelector: {}
            
            retention: 15d
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 1
                memory: 2Gi
        
        nodeExporter:
          hostRootfs: true
          extraArgs:
            - --path.rootfs=/host
          extraMounts:
            - name: root
              mountPath: /host
              readOnly: true
              mountPropagation: HostToContainer

        ## Alertmanager
        alertmanager:
          apiVersion: v2

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # חובה בגרסאות 80+ עבור ה-CRDs
    automated:
      prune: true
      selfHeal: true