---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-key
  namespace: prod-us
spec:
  encryptedData:
    GEMINI_API_KEY: AgB6QrvGg+4FHM6zqv0Fc5xFSU99G86SkYVRhWp6tbz4Sla9UYmSK493/YBUKU/kP8TJw/ysqIcfnCiaMxcbPWVSHFKLRSX1LyUz7y74+v0LbWjeEMXBxXEujoR7oGGEnA2FNbWa91MTz4jrJea0Arjfu5BiiqYA2b5QcNsIywSHk8unlWmsBsa6rSF9E/LP87ygvn1mnRqbItDpAAo6/niKxHjZeGPG1b88KsXk5ivVaSvZa+vK2afsELIajoSK16D1hbC/8X+fRdhZ+GTvtwiXMjNzRQA67lZ0l1TXHC5sEE7+s9mBcVXiyjuLHPtb1dMJtb6R6XmJ/6c8y7N0ookAWs8stgmVOCln+2PYHdqlcoJwCFNSmRjHAg/phM/P8n+KG9/RpEDS6zWSIIBa3fCPJknFJOJon2UIih8qoT1k0MenH7hE3OqF8TuGDRUTFSlV//wWIxBjl8tvJPydJJICoYou1Z24aVXT7DZhT429oJhmeKxlBFtJlTjxTLmFa/woxfUJyNhP+13fkt1+IiRcUMoSyDxaQ4OZ23FtCYys1CZHUsxcrAp1GEYZUIpctd4BFusnFqG2jii+GTTWNcJaC2lJOF8kIVeeA1Vg1b8Ag9Q/WIt3o7h9C1CBuDEILpHRfp1066nHWarP5yfUSDIt6T4DhIgw2f4I91kZD69Mh7qJimdTk7iULMeMkeadGWNMFpoByGhaNcg2M6645KyBjxDRvjJfcqbfKSq4Hkc+1hP0/RiV8cg=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-key
      namespace: prod-us
    type: Opaque
