---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-key
  namespace: qa
spec:
  encryptedData:
    GEMINI_API_KEY: AgCgeuqn1CP7j+Z+3MlJ2ypPfKOWGkMUPYkTEuLLNia3Kka0CdWKt1idjOkmCB+vnWWg8E2MmC0ldZ4alufFkZmnZwjclQPQWPkqOJaxqzRv/JREPDLudc0zXxeurh8lfpcQTSW7wN8Z0dhrHgnzn3VynXY83IEJ6jHusi6lQTDgJL9DnE2HjyJfH9mljDZvJVnvVa8nyZ3Gstj4VeCeV+YrN1KpkLnXrdAoTjFLE748kketa6RE1zXQxWCR2xZ/rLBaTkHwZjcPEOE0H/c4SJwIk/OK3hfcFRrlcVPitEgw04PXyICXvRqDUTsCrnw4zdgq+Z5ESOY18PQq73gR+eCWN4wVv7ttBpWLWCVxzeuoPfAgEszcXoLnLb/xLXhOOnxaD/49LwJuOqev8YfMxAJEr5xRJ0kv00yVZt3JIn5ZllEiNLA97hhzPMb1tFqSHSFajs98xfPN9r6kNK2X5GqakK/Lnlz5frADkfDH0COrOHzVUE4svAXOU6VzJ/ytcp538ytjm8mGxbAhOyVABBnyf29VbpiQ1Q4rCG58COXyb4eMm87+F+NsUSTmYF31R1w3G61xM+Sjlfpp9/ZhUa/tJ2qrFDZk7/K6xULlZRQ1P01WW82Xtqx8gqegJuzqPfEv2oWJQpDRnpmBsWcxCFUBRDa46vLMKyWs3bNLVaarHu5YAgRbD87w9053KobkOS957VHW0cvNTfOLGtBURBuMmcF64nV8Bx8yjUxLGelmPTEmzhI9s38=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-key
      namespace: qa
    type: Opaque
