---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-key
  namespace: prod-eu
spec:
  encryptedData:
    GEMINI_API_KEY: AgA7YScX/IvlxoMk9HyIUTzc3U08fwuM15uaeeXc9SkuTxNyn5roQwXB6YyB69MHYUUhYccTzP7RHImjaqBiWOmnGbLau983HfvwzXyh1Q6F+EGXLIQzY3jNyigT8PtPep8WG5eMiEjVgpt93KVPmXAS+E5hwv4+VxE+j5tHSV0zjDAX8ZFungH3m/yNQex45xY09LNJqBMkmvCjYCJzIyRHaa3CMFdxAlWQ/HIG94GhO3eECQGpDbPu9AsHqxGFYwEpD1j19SHJm4c330C34hN1gpSzDnM5ecknXlJ+sYZrZp/k2aMzcqe6FiQLHcAg3crUpHQ0d2ua108eEGwumuMoHg0MwdWv5Y1zVAAbczCPGekehhxTQr5ewtAWU6DHM2g4b/ivdg8OeL3bRkSiUuMGVTJCnxX+Xy9Sj3IGqRTZP6xEgcTql9FIACE5ocuQ//xJj7PguBu8EBhm8v2VY5zJblWhb8XSi8Rc2qIDtJ392OwLKYexf00V/kjyhPA6WxlguyEc0fIX1lZuewmmAnx8528YuKaSugK3fyROtaCko4b8dXjoZdjoEPzOzotUQcqe3AqF3A6WUllTJQspflLSekLqiQjUGFkA6zQtEyfSIRk84O34ku8BEEO6UFeQize6GXlgKly+qJQKMp+dBYBRYZWmVRoXWahhonTwk/uSBJrkTH6+qHbHit2+nqvd7pR7pRRCpeZQdEawk8YB3BQEqer1xtZvvJCG25nikbKsSJFceg5fANc=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-key
      namespace: prod-eu
    type: Opaque
