---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-key
  namespace: staging
spec:
  encryptedData:
    GEMINI_API_KEY: AgCiQH5dySXcwrVBPj2a9kx6b9Ope/oJ7bWr6xnUG2ndRQgN5KuIU5vCW50L52kKy1R5y7SRnxWEABWtLaWUry3kLOAo5OhL8o2UVACmoicGhox5vLAe4dRT7ir3UaKrNmWO0xqQa/ocCn49HvpKJssTr8OEVUPpeEwyG4Ow5zoxYbTFx/VJR1A+DmZCjr4j4XqCyepXy1jB8U8igytGjrl23pZEKX4vmP1F/JCnAL0RYSjH3vBXCXaz4vKcQl1vPeh/5ukvhIdfgkQog7apd0hHhQFym8GeyXlH9I1ygM8IUzq4nmWZK23PlGgFnU3xCgyuB2PhOZNCxV0/2qEAeltGKMfdd3TCM4gyxNqk5z4IrkL8cwTb4lMoR/BGQ8nzFFh5dsB8i+03xTBUgV9E394EoEydc1SqAnNQkIJtzZ/ozviLJJTea5z31l+MlY2LrKTutGYvLMCUr/ohq4TsSkJ6zcp+Sh6IrEVWxE4UTMfohbJwZXjyTt0XgeybITmImJlMIXSQg3ZhWEN/41z7GJo0qtuWugDt8NMhKTglDggQE6YT9eD2V2c+MWaKTjZfhtHp9ysngT0lG7D/sE0itmZHJh7jPvsHIxzNIweIPnXjS0AtHWt0/z/srGYB4XC+/PQrMzRJcpyay/OMr7dUnFGdDD13g9Uz3Vv6CArt/rPKmLUTjW3KiRYOD7u/oNjPy4F5/Lcbh0p8LPBI7MAv88sJN3BVnowATtU6lhaLOAY5hNm+QwkilG4=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-key
      namespace: staging
    type: Opaque
