---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-key
  namespace: amiranet
spec:
  encryptedData:
    GEMINI_API_KEY: AgAO1+8i+/z1w+PwWJGiE3Q0BceJOQNflyriUvdezp1b9gbsvufbw5cIfQ5QYsUVA4Dmr33nAC/7/6/099XzXXCyTeRVFCoQUFBkm3nj5HtJp47Im/IOA4T6jV4gqVZabEOA2xE1HhIj6LqdSLV4asN0mmmJ4oSC50ZpnVUApgycZMhjyhQ6ThEeeDVYW9mSpOMT38oblCu8PS//wE9SMIZLX/qCVChVnDzR/fYrAngtcdFXMdBC1u5wc9TC7nQVfxmMHXZvyw006n7pAK2wZ1O+72+9EjATNXg4fk+gTpT4kjWnd8H/Tu/8tfreR5gWAmcq79G+RKQq5AYYo8IKJbmy6nBkLfCDFOem/LLUxrha6O05YNijbp1aGmNSp0gUVEusbghnxNr9+Fw2Rp1wKVr9xkRJzKDRbuJ87+pleXY8zzATYQcDHv8p3c4oxLCTzl/HxDoWQNI3SgtPPZksTjo4Vg3e1GDM5DEh2mKURcXxLFfJ8TUGfft3sSnA8myX8hCJJz6zSeyRzwHzQL6LFljqQumyF/0wLZ/Ysg7sa+EWSvpxiJJW+JkN5DMFqMQhAtukIpTZQi8FuX4NkHLBhuGaTFlO/GQSiVylNFWrfdH/B6OPsUh96OFOXCshpXmPG4aS2AAvqk2RT+9OVn7zDW5585y8sAnYniBVbJhvPRC3FoV8Ho8VcTR3/HoRfJWtAj+MCDQVwQ9w5t/vrWL2I49Fisdju4vrB9NSX6WqJOO4SoF+BhgS1Tbb
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-key
      namespace: amiranet
    type: Opaque
