---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-key
  namespace: amiranet
spec:
  encryptedData:
    GEMINI_API_KEY: AgCT+yJHgHzOnxQx8Dwvn7fbLEACfEFWRp76Wi1AJx5ZpGycUJ2Y1oPtHz9PIZ3EXoyQr9KMSAHvZjGVJPMEb5cbyZPGdCVN5hmXjKg2VQ3/nkV+e5Fg0CmLZm90m1Hb1g8z8CeJWN19J5ehEZg55fvwfFmArumd9OLikWE0nnW4SsnK8w2YCNiwyiSRENYq4eMIbutpezGY+K6l6LuiIunJXbAdNrpnd/FVFYVP+hguhrbJq6jgqXDYXPBOL4zqAhbgDPqywQ4MgFWpA+GutA3UXHhB3Wnqvf/FMRXLxDdGaH3pVMudbLM5laBm13kQs9FywPzhiJBuhnUlh/ppIHCoyiZptCrsUe2Dw2rYdz5Nzz5iPUGgIRqXdbSpj4wSxKBSxhUU/PtkCXYlHaRdoHHZHYNfQa+Cv62VYdWinRl0xgX1xCPnAKjrhhWrk8Urq0TQun2/I7iNa2ZJJPrtWBq/+cSV8y4aNP8CMRhewz6dTh6ZSeTq2AHWXM1ndcw9yznnI4t1ac3K5MQ5kyQMvHLS1fLDpOaN8E530cgvKYIDPgeyu2P/cUN7xJjeql2tfcqhtkdmo6wmmAPkIZBf5GSZM+6wT1foOX41d20gi8Wz0SF4yaB1Z6GXgMr3LyJkSgH/uTnUpaGkKetFCBDs4X3HEAoR4yITsvKJdCHBae9mrctqqNVrMq49VJEtzyablHOkCCtJsF4Blqvp+XCn4JJ6oDNyH2xg0YPJeTEhdMhrsv1aTWbQMe8=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-key
      namespace: amiranet
    type: Opaque
