apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: amiranet
spec:
  weighted:
    services:
      - name: amiranet-service-stable
        port: 80
      - name: amiranet-service-canary 
        port: 80
