{{- if eq .Release.Namespace "qa" }}
{{- .Files.Get "keys/gemini-api-key-qa.yaml" }}
{{- end }}
{{- if eq .Release.Namespace "staging" }}
{{- .Files.Get "keys/gemini-api-key-staging.yaml" }}
{{- end }}
{{- if eq .Release.Namespace "prod-us" }}
{{- .Files.Get "keys/gemini-api-key-prod-us.yaml" }}
{{- end }}
{{- if eq .Release.Namespace "prod-eu" }}
{{- .Files.Get "keys/gemini-api-key-prod-eu.yaml" }}
{{- end }}
