# Default values for my-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.

# Kubernetes settings
replicaCount: 1
imageVersion: "v1.0"
resources:
    requests:
        memory: "256Mi"
        cpu: "250m"
    limits:
        memory: "512Mi"
        cpu: "500m"

# Service configuration
service: 
    type: ClusterIP 
    port: 80 
    targetPort: 5000 